# Generated by Django 3.2.16 on 2022-10-12 15:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachFiles',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('imgUrl', models.CharField(max_length=100, verbose_name='图片地址')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1)),
                ('guid', models.UUIDField(default=uuid.UUID('933c381b-6c5c-4e8d-b587-f5023717c8bb'), primary_key=True, serialize=False, verbose_name='图片主键')),
            ],
            options={
                'verbose_name': '图片附件表',
                'verbose_name_plural': '图片附件表',
                'db_table': 'dl_img_file',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goodName', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goodIntorduction', models.CharField(max_length=500, verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('priceUnit', models.SmallIntegerField(choices=[(1, '元'), (2, '美元'), (3, '港币')], default=1, verbose_name='价格单位')),
                ('stock', models.IntegerField(default=1, verbose_name='库存')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='商品状态')),
                ('saleCount', models.IntegerField(default=0, verbose_name='商品销量')),
            ],
            options={
                'verbose_name': '商品sku表',
                'verbose_name_plural': '商品sku表',
                'db_table': 'dl_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='商品spu名称')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品spu表',
                'verbose_name_plural': '商品spu表',
                'db_table': 'dl_goods_spu',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='种类名称')),
                ('logo', models.CharField(max_length=50, verbose_name='logo图片地址')),
                ('imgGuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.attachfiles', verbose_name='图片id')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
                'db_table': 'dl_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('display_type', models.SmallIntegerField(choices=[(0, '标题'), (1, '图片')], default=1, verbose_name='展示类型')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodssku', verbose_name='商品SKU')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodstype', verbose_name='商品类型')),
            ],
            options={
                'verbose_name': '主页分类展示商品',
                'verbose_name_plural': '主页分类展示商品',
                'db_table': 'dl_index_type_goods',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='活动名称')),
                ('url', models.URLField(verbose_name='活动链接')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.attachfiles', verbose_name='图片id')),
            ],
            options={
                'verbose_name': '主页促销活动',
                'verbose_name_plural': '主页促销活动',
                'db_table': 'dl_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.attachfiles', verbose_name='图片id')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodssku', verbose_name='商品')),
            ],
            options={
                'verbose_name': '首页轮播商品',
                'verbose_name_plural': '首页轮播商品',
                'db_table': 'dl_index_banner',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='goodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodstype', verbose_name='商品种类'),
        ),
        migrations.AddField(
            model_name='goodssku',
            name='imgGuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.attachfiles', verbose_name='图片id'),
        ),
    ]
