# Generated by Django 3.2.16 on 2022-10-12 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfiles',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('e6df32d6-5f61-45a5-93bd-193005ad2d1e'), primary_key=True, serialize=False, verbose_name='图片主键'),
        ),
    ]
