# Generated by Django 3.2.16 on 2022-10-15 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_attachfiles_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfiles',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1229cc7f-0498-449f-83ea-f2abb8e2fa3b'), primary_key=True, serialize=False, verbose_name='图片主键'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goodIntorduction',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goodName',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goodType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.goodstype', verbose_name='商品种类'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='imgGuid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.attachfiles', verbose_name='图片id'),
        ),
        migrations.AlterField(
            model_name='goodsspu',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='商品spu名称'),
        ),
    ]
