# Generated by Django 3.2.16 on 2022-10-15 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20221015_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssku',
            name='spuGuid',
            field=models.IntegerField(blank=True, default=0, verbose_name='商品对应的spu主键'),
        ),
        migrations.AlterField(
            model_name='attachfiles',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('47e6dd38-94f6-4a98-96ff-434dc6899c94'), primary_key=True, serialize=False, verbose_name='图片主键'),
        ),
    ]
