# Generated by Django 3.2.16 on 2022-10-22 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20221015_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfiles',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('559fb449-7a1f-488c-a91d-4c82f9ad6c7e'), primary_key=True, serialize=False, verbose_name='图片主键'),
        ),
    ]
