# Generated by Django 3.2.16 on 2022-10-23 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_attachfiles_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfiles',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('9ff5db34-b90c-4f5d-b706-3c0137d6b00f'), primary_key=True, serialize=False, verbose_name='图片主键'),
        ),
    ]
