# Generated by Django 3.2.16 on 2022-10-12 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('guid', models.UUIDField(primary_key=True, serialize=False, verbose_name='订单主键，使用UUID')),
                ('payWay', models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信支付'), (3, '信用卡')], default=1, verbose_name='支付方式')),
                ('goodsCount', models.SmallIntegerField(default=0, verbose_name='订单内商品总数')),
                ('payGoods', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='订单商品总金额')),
                ('payTraffic', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='订单运费')),
                ('status', models.SmallIntegerField(choices=[(0, '提交订单'), (1, '未支付'), (2, '已支付'), (3, '已发货'), (4, '待评价'), (5, '已完成')], default=0, verbose_name='订单状态')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户主键')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'dl_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('guid', models.UUIDField(primary_key=True, serialize=False, verbose_name='订单中的商品信息主键，使用UUID')),
                ('skuCount', models.IntegerField(default=0, verbose_name='商品数量')),
                ('skuPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('comment', models.CharField(max_length=500, verbose_name='商品评论')),
                ('orderGuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderinfo', verbose_name='对应订单主键')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'dl_order_goods',
            },
        ),
    ]
