# Generated by Django 3.2.16 on 2022-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20221015_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='tradeNo',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='订单编号'),
        ),
    ]
